/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luo_bing_com_bingproject_ndk_demo_HelloNDK */

#ifndef _Included_luo_bing_com_bingproject_ndk_demo_HelloNDK
#define _Included_luo_bing_com_bingproject_ndk_demo_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luo_bing_com_bingproject_ndk_demo_HelloNDK
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luo_bing_com_bingproject_ndk_1demo_HelloNDK_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
